[package]
name = "aws_lambda_benchmarking"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"


[dependencies]
structopt = "0.3.21"
sha2 = "0.9.3"


[profile.release]
lto = 'fat'
codegen-units = 1
