[package]
name = "aws_lambda_language_benchmarking"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2021"


[dependencies]
# For CLI parsing.
structopt = "0.3.26"

# For SHA256 hashing.
sha2 = "0.10.8"


[profile.release]
lto = 'fat'
codegen-units = 1
