[package]
name = "aws_lambda_language_benchmarking"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"


[dependencies]
# Arg parsing
structopt = "0.3.21"

# Hashing
sha2 = "0.9.5"


[profile.release]
lto = 'fat'
codegen-units = 1
