python3-local-formatting:
  stage: formatting
  image: python:3
  before_script:
    - pip install pycodestyle
  script:
    - cd python3/local/
    - pycodestyle src/main.py --max-line-length=140
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


python3-local-compiling:
  stage: compiling
  image: python:3
  script:
    - cd python3/local/
    - python -m py_compile src/main.py
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
