stages:
  - clean-git-history-checking
  - conventional-commits-linting
  - formatting
  - linting
  - vetting
  - module-tidying
  - compiling


clean-git-history-checking:
  stage: clean-git-history-checking
  image: rust
  before_script:
    - cargo install clean_git_history
  script:
    # Check all the commits in the branch.
    - /usr/local/cargo/bin/clean_git_history --from-reference "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - if: $CI_MERGE_REQUEST_ID


conventional-commits-linting:
  stage: conventional-commits-linting
  image: rust
  before_script:
    - cargo install conventional_commits_linter
  script:
    # Lint all the commits in the branch.
    - /usr/local/cargo/bin/conventional_commits_linter --from-reference "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --allow-angular-type-only
  rules:
    - if: $CI_MERGE_REQUEST_ID


include:
  - local: .gitlab/ci/go/aws.yml
  - local: .gitlab/ci/go/local.yml
  - local: .gitlab/ci/nodejs/aws.yml
  - local: .gitlab/ci/nodejs/local.yml
  - local: .gitlab/ci/python/aws.yml
  - local: .gitlab/ci/python/local.yml
  - local: .gitlab/ci/rust/aws.yml
  - local: .gitlab/ci/rust/local.yml
