VERSION 0.7


COPY_CI_DATA:
    COMMAND
    COPY --dir "ci/" "./"


COPY_SOURCECODE:
    COMMAND
    DO +COPY_CI_DATA
    COPY --dir "src/" "./"


python-base:
    FROM python:3-slim@sha256:914bf5c12ea40a97a78b2bff97fbdb766cc36ec903bfb4358faf2b74d73b555b
    WORKDIR /tmp/aws_lambda_language_benchmarking
    DO +COPY_SOURCECODE


check-python-formatting:
    FROM +python-base
    RUN pip3 install "autopep8"
    RUN ./ci/check-python-formatting.sh


golang-base:
    FROM golang:1.24.3@sha256:4c0a1814a7c6c65ece28b3bfea14ee3cf83b5e80b81418453f0e9d5255a5d7b8


sh-formatting-base:
    FROM +golang-base
    RUN go install mvdan.cc/sh/v3/cmd/shfmt@v3.6.0
    DO +COPY_CI_DATA


check-shell-formatting:
    FROM +sh-formatting-base
    RUN ./ci/check-shell-formatting.sh


check-formatting:
    BUILD +check-python-formatting
    BUILD +check-shell-formatting


fix-python-formatting:
    FROM +python-base
    RUN pip3 install "autopep8"
    RUN ./ci/fix-python-formatting.sh
    SAVE ARTIFACT "src/" AS LOCAL "./"


fix-shell-formatting:
    FROM +sh-formatting-base
    RUN ./ci/fix-shell-formatting.sh
    SAVE ARTIFACT "ci/" AS LOCAL "./"


fix-formatting:
    BUILD +fix-python-formatting
    BUILD +fix-shell-formatting


ubuntu-base:
    FROM ubuntu:24.04@sha256:6015f66923d7afbc53558d7ccffd325d43b4e249f41a6e93eef074c9505d2233
    # https://askubuntu.com/questions/462690/what-does-apt-get-fix-missing-do-and-when-is-it-useful
    RUN apt-get update --fix-missing


check-shell-linting:
    FROM +ubuntu-base
    RUN apt-get install shellcheck -y
    DO +COPY_CI_DATA
    RUN ./ci/check-shell-linting.sh


check-linting:
    BUILD +check-shell-linting


compile:
    FROM +python-base
    RUN ./ci/compile.sh
