VERSION 0.7


COPY_CI_DATA:
    COMMAND
    COPY --dir "ci/" "./"


INSTALL_DEPENDENCIES:
    COMMAND
    COPY "package.json" "./"
    COPY --if-exists "package-lock.json" "./"
    RUN npm ci


COPY_SOURCECODE:
    COMMAND
    DO +COPY_CI_DATA
    COPY --dir "src/" "./"


nodejs-base:
    FROM node:22.13.1@sha256:debe7ff79b1a92c699629d685c4b69ba531172d6dfd89e145fa528bfb18eefb7
	DO +INSTALL_DEPENDENCIES
    DO +COPY_SOURCECODE


check-nodejs-formatting:
    FROM +nodejs-base
    RUN ./ci/check-nodejs-formatting.sh


sh-formatting-base:
    FROM golang:1.22.1@sha256:0b55ab82ac2a54a6f8f85ec8b943b9e470c39e32c109b766bbc1b801f3fa8d3b
    RUN go install mvdan.cc/sh/v3/cmd/shfmt@v3.6.0
    DO +COPY_CI_DATA


check-shell-formatting:
    FROM +sh-formatting-base
    RUN ./ci/check-shell-formatting.sh


check-formatting:
    BUILD +check-nodejs-formatting
    BUILD +check-shell-formatting


fix-nodejs-formatting:
    FROM +nodejs-base
    RUN ./ci/fix-nodejs-formatting.sh


fix-shell-formatting:
    FROM +sh-formatting-base
    RUN ./ci/fix-shell-formatting.sh
    SAVE ARTIFACT "ci/" AS LOCAL "./"


fix-formatting:
    BUILD +fix-nodejs-formatting
    BUILD +fix-shell-formatting


ubuntu-base:
    FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab
    # https://askubuntu.com/questions/462690/what-does-apt-get-fix-missing-do-and-when-is-it-useful
    RUN apt-get update --fix-missing


check-shell-linting:
    FROM +ubuntu-base
    RUN apt-get install shellcheck -y
    DO +COPY_CI_DATA
    RUN ./ci/check-shell-linting.sh


check-linting:
    BUILD +check-shell-linting
