.PHONY: default
default:
	@echo "No default target."

.PHONY: check-nodejs-formatting
check-nodejs-formatting:
	npx prettier --check .

.PHONY: fix-nodejs-formatting
fix-nodejs-formatting:
	npx prettier --write .
