nodejs-local-formatting:
  stage: formatting
  image: node
  before_script:
    - npm -g install js-beautify
  script:
    - cd nodejs/local/
    - for i in $( du -a ./src/ | awk '{print $2}' | grep -i "[.]js$" ); do
    - echo $i
    - js-beautify $i > temp.txt
    - cmp $i temp.txt || exit
    - done
  rules:
    - if: $CI_MERGE_REQUEST_ID


nodejs-local-linting:
  stage: linting
  image: node
  before_script:
    - npm -g install eslint
  script:
    - cd nodejs/local/
    - eslint ./src/
  rules:
    - if: $CI_MERGE_REQUEST_ID
