go-local-formatting:
  stage: formatting
  image: golang
  script:
    - cd go/local/
    - MALFORMATTED_FILES=$(gofmt -s -l ./src/ | wc -l)
    - test "$MALFORMATTED_FILES" -eq 0
  rules:
    - if: $CI_MERGE_REQUEST_ID


go-local-linting:
  stage: linting
  image: golang
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - cd go/local/
    - LINTING_ISSUES=$(/go/bin/golint ./src/ | wc -l)
    - test "$LINTING_ISSUES" -eq 0
  rules:
    - if: $CI_MERGE_REQUEST_ID


go-local-vetting:
  stage: vetting
  image: golang
  script:
    - cd go/local/
    - go vet ./src/
  rules:
    - if: $CI_MERGE_REQUEST_ID


go-local-compiling:
  stage: compiling
  image: golang
  script:
    - cd go/local/
    - go build -o main ./src/
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"
