name: Continuous Integration (CI)

on: pull_request

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [rust/aws, rust/local]
        language: [rust, shell]
    steps:
      - name: Checkout code.
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Check formatting.
        run: cd "${{ matrix.directory}}" && make check-${{ matrix.language }}-formatting
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [rust/aws, rust/local]
        language: [rust]
    steps:
      - name: Checkout code.
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Check linting.
        run: cd "${{ matrix.directory}}" && make check-${{ matrix.language }}-linting
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [rust/aws, rust/local]
    steps:
      - name: Checkout code.
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Compile.
        run: cd "${{ matrix.directory}}" && make compile
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [rust/aws, rust/local]
    steps:
      - name: Checkout code.
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Unit test.
        run: cd "${{ matrix.directory}}" && make unit-test
